-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtyal3p7NznzBXYlQ
4bzkqJ+gUfk5b1uoUlKyraSCY7SgCgYIKoZIzj0DAQehRANCAASwmuhbskX/KKvx
UC46eahFX3bkzKNcS5Ga3+ZZPmXsVYmH92KgOGbo3UH/dOc4WeNG9cSVHrt3EYXk
sa7zJ0vl
-----END PRIVATE KEY-----